#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of droplets
# created from your image.  Things ike generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

set -eu

mkdir -p /etc/code-server
touch /etc/code-server/pass
chmod 0600 /etc/code-server/pass
cat /dev/urandom | head -c 8 | base64 >> /etc/code-server/pass
