#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
The password for accessing code-server is configured on first
login and is then written to /etc/code-server/pass.

Once the password is configured, you can access code-server at https://${myip}.

code-server runs as a systemd service unit and will start at boot.
You can access its logs with \`journalctl -fu code-server\`.

If you want to change the password, delete /etc/code-server/pass and
then run /opt/coder/code-server-pass.sh.

More docs are available at https://github.com/cdr/code-server.
EOF
