#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
The password for accessing code-server is randomly generated
and placed in /etc/code-server/pass.

You can access code-server at https://${myip}.

If you wish to change the password, just modify /etc/code-server/pass
and then restart the code-server systemd unit.

Docs for code-server are available at https://github.com/cdr/code-server.
EOF
